### ISSUE TITLE
After registration, user cannot add an organization (via change-preferences site)

### ISSUE THREAD

**Issue by kstosiek** [dreamer/zapisy_zosia#26] opened 2010-01-27 01:32 UTC
As described above.

**Comment by dreamer** [comment] 2010-01-28 18:50
invalid - by design / add not to UI, that they won't be able to change this after registration

**Comment by fsieczkowski** [comment] 2010-02-04 16:53
Added info to UI, closing as wontfix

**Closed as completed by fsieczkowski** 2010-02-04 16:53 UTC
Labels: bug
